name: "Release Pipeline"
on:
  workflow_dispatch:
  # Todo: Restrict
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+$"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-latest-version
        uses: ./.github/actions/get-latest-version
        with:
          current_commit_only: true
      - name: run-tests
        uses: ./.github/actions/build-environment
        with:
          build_args: --test --version=${{ env.LATEST_VERSION }}
      - name: release-components
        uses: ./.github/actions/build-environment
        with:
          build_args: --release --build --force --version=${{ env.LATEST_VERSION }}
          pypi_test_token: ${{ secrets.PYPI_TEST_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
