name: build-pipeline

on:
  workflow_dispatch:
    inputs:
      build_args:
        description: "Arguments passed to build script."
        required: false
      working_directory:
        description: "Working directory from where the build command is run."
        required: false

env:
  BUILD_ARGS: ${{ secrets.BUILD_ARGS }}
  WORKING_DIRECTORY: ${{ secrets.WORKING_DIRECTORY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-build-scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: --test --version=0.0.0
          working_directory: ${{ env.WORKING_DIRECTORY }}
