name: test-pipeline

on: [workflow_dispatch, push, pull_request]

env:
  BUILD_ARGS: "--test"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set-input-build-args
        if: ${{ github.event.inputs != null  &&  github.event.inputs.build_args != null}}
        run: echo "::set-env name=BUILD_ARGS::${{ github.event.inputs.build_args }}"
      - uses: actions/checkout@v2
      - name: run-build-scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: ${{ env.BUILD_ARGS }}
